version: '3'

tasks:
  default:
    cmds:
      - git pull
      - php artisan migrate
      - npm run build
      - sudo systemctl status ekspedisi-queue

  push:
    cmds:
      - git add .
      - git commit -m {{ .CLI_ARGS }}
      - git push
