version: '3'

tasks:
  default:
    cmds:
      - git pull
      - composer install --no-dev --optimize-autoloader
      - php artisan migrate
      - php artisan optimize:clear
      - php artisan filament:optimize-clear
      - php artisan optimize
      - php artisan filament:optimize
      - npm run build
      - sudo systemctl restart ekspedisi-queue
      - sudo systemctl status ekspedisi-queue

  push:
    cmds:
      - git add .
      - git commit -m {{ .CLI_ARGS }}
      - git push
